# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  # branches:
  #   include:
  #     - master
  tags:
    include:
      - v*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

# - script: |
#     export githubTag=$(git describe --abbrev=0 --tags)
#     echo "##vso[task.setvariable variable=githubTag]$githubTag"
#   condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
#   displayName: Set tag to env variable githubTag
#   failOnStderr: true

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# ASP.NET Core (.NET Framework)
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)'


- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_miakh'
    repositoryName: 'miakh/GPhotosMirror'
    action: 'create'
    target: '$(Build.SourceVersion)'
    assets: '$(Build.ArtifactStagingDirectory)/*.zip'
    tagSource: 'gitTag'
    # title: '$(githubTag)'
    releaseNotesSource: 'inline'
    isPreRelease: false
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
