# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# ASP.NET Core (.NET Framework)
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)'


- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_miakh'
    repositoryName: 'miakh/GPhotosMirror'
    action: 'create'
    target: '$(Build.SourceVersion)'
    assets: '$(Build.ArtifactStagingDirectory)/*.zip'
    tagSource: 'gitTag'
    title: 'v$(Build.BuildNumber)'
    releaseNotesSource: 'inline'
    isPreRelease: false
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'








